baseURL: "https://mingray98.github.io/mrcodingroom"
title: MRcodingRoom
paginate: 10
theme: PaperMod
languageCode: zh-tw # en-us

hasCJKLanguage: true
enableInlineShortcodes: true
enableEmoji: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

permalinks:
  post: "/:title/"
  # post: "/:year/:month/:day/:title/"

defaultContentLanguage: zh-tw
defaultContentLanguageInSubdir: true

languages:
  zh-tw:
    languageName: "Chinese"
    weight: 1

    menu:
      main:
        - identifier: search
          name: Search
          url: search
          weight: 2
        - identifier: home
          name: Home
          url: /
          weight: 1
        - identifier: Archive
          name: Archives
          url: archives
          weight: 3
        - identifier: categories
          name: Categories
          url: categories
          weight: 5
        - identifier: tags
          name: Tags
          url: /tags
          weight: 6
        - identifier: about
          name: about
          url: /about
          weight: 4

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  homeInfoParams:
    Title: Home
    Content: 其實是中文部落格，但硬要打一點英文
  socialIcons:
    - name: github
      url: "https://github.com/mingray98"

  env: production
  description: "MR的coding筆記"
  author: MingRay
  # author: ["Me", "You"] # multiple authors

  defaultTheme: light # defaultTheme: light or  dark
  disableThemeToggle: false
  DateFormat: "2006-01-02"
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecialistPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideFooter: false
  ShowWordCounts: true
  VisitCount: true

  ShowLastMod: true

  ShowToc: true
  TocOpen: true

  comments:
    true
    #   url: "img/phone.png"

  # editPost:
  #     URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  #     Text: "Suggest Changes" # edit text
  #     appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    favicon: "img/logo.png"
    favicon16x16: "img/logo.png"
    favicon32x32: "img/logo.png"
    apple_touch_icon: "img/logo.png"
    safari_pinned_tab: "img/logo.png"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 1
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary"]

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    # style: monokai
    style: darcula

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
